jobs:
- job: 'Build_and_Test_Ubuntu_1604'
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      Python35:
        parameters.python: '3.5'
      Python36:
        parameters.python: '3.6'
      Python37:
        parameters.python: '3.7'
      PyPy3:
        parameters.python: 'pypy3'
  variables: { parameters.os: linux }
  steps:
  - template: azure-pipelines-steps.yml
- job: 'Build_and_Test_Mac_1013'
  pool:
    vmImage: 'macOS-10.13'
  strategy:
    matrix:
      Python35:
        parameters.python: '3.5'
      Python36:
        parameters.python: '3.6'
      Python37:
        parameters.python: '3.7'
      PyPy3:
        parameters.python: 'pypy3'
  variables: { parameters.os: mac }
  steps:
  - template: azure-pipelines-steps.yml
- job: 'Build_and_Test_WinServer_2016'
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      Python35:
        parameters.python: '3.5'
      Python36:
        parameters.python: '3.6'
      Python37:
        parameters.python: '3.7'
      PyPy3:
        parameters.python: 'pypy3'
  variables: { parameters.os: windows }
  steps:
  - template: azure-pipelines-steps.yml