jobs:
- job: 'Build_and_Test_Ubuntu_1604'
  pool:
    vmImage: 'ubuntu-16.04'
  variables:
    os.version: 'linux'
  strategy:
    matrix:
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
      PyPy3:
        python.version: 'pypy3'
  steps:
  - template: azure-pipelines-steps.yml
- job: 'Build_and_Test_Mac_1013'
  pool:
    vmImage: 'macOS-10.13'
  variables:
    os.version: 'mac'
  strategy:
    matrix:
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
      PyPy3:
        python.version: 'pypy3'
  steps:
  - template: azure-pipelines-steps.yml
- job: 'Build_and_Test_WinServer_2016'
  pool:
    vmImage: 'vs2017-win2016'
  variables:
    os.version: 'windows'
  strategy:
    matrix:
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
      PyPy3:
        python.version: 'pypy3'
  steps:
  - template: azure-pipelines-steps.yml