jobs:
- job: 'Build_and_Test_Ubuntu_1604'
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
  steps:
  - template: azure-pipelines-unixy-steps.yml
- job: 'Build_and_Test_Mac_1013'
  pool:
    vmImage: 'macOS-10.13'
  strategy:
    matrix:
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
  steps:
  - template: azure-pipelines-unixy-steps.yml
- job: 'Build_and_Test_Win_7'
  pool:
    vmImage: 'vs2015-win2012r2'
  strategy:
    matrix:
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
  steps:
  - template: azure-pipelines-unixy-steps.yml