jobs:
- job: 'Build_and_Test'
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'

  steps:
    template: azure-pipelines-unixy-steps.yml