resources:
  containers:
  - container: manylinux1
    image: quay.io/pypa/manylinux1_x86_64
jobs:
- job: 'Build_and_Test_manylinux1'
  pool:
    vmImage: 'ubuntu-16.04'
  container: manylinux1
  strategy:
    matrix:
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
      PyPy3:
        python.version: 'pypy3'
  steps:
  - template: azure-pipelines-steps.yml
- job: 'Build_and_Test_Mac_1013'
  pool:
    vmImage: 'macOS-10.13'
  strategy:
    matrix:
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
      PyPy3:
        python.version: 'pypy3'
  steps:
  - template: azure-pipelines-steps.yml
- job: 'Build_and_Test_WinServer_2016'
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'
      PyPy3:
        python.version: 'pypy3'
  steps:
  - template: azure-pipelines-steps.yml