resources:
  containers:
  - container: manylinux1
    image: quay.io/pypa/manylinux1_x86_64
jobs:
- job: 'Build_and_Test_manylinux1'
  pool:
    vmImage: 'ubuntu-16.04'
  container: manylinux1
  strategy:
    matrix:
      Python35:
        python.version: '3.5'
        python.command: '/opt/python/cp35-cp35m/bin/python'
      Python36:
        python.version: '3.6'
        python.command: '/opt/python/cp36-cp36m/bin/python'
      Python37:
        python.version: '3.7'
        python.command: '/opt/python/cp37-cp37m/bin/python'
      PyPy3:
        python.version: 'pypy3'
        pypy.version: 'pypy3.5-7.0.0-linux_x86_64'
        python.command: '$(pypy.version)-portable/bin/./pypy3'
  steps:
  - template: azure-pipelines-steps.yml
# - job: 'Build_and_Test_Mac_1013'
#   pool:
#     vmImage: 'macOS-10.13'
#   strategy:
#     matrix:
#       Python35:
#         python.version: '3.5'
#         python.command: 'python'
#       Python36:
#         python.version: '3.6'
#         python.command: 'python'
#       Python37:
#         python.version: '3.7'
#         python.command: 'python'
#       PyPy3:
#         python.version: 'pypy3'
#         python.command: 'python'
#   steps:
#   - template: azure-pipelines-steps.yml
# - job: 'Build_and_Test_WinServer_2016'
#   pool:
#     vmImage: 'vs2017-win2016'
#   strategy:
#     matrix:
#       Python35:
#         python.version: '3.5'
#         python.command: 'python'
#       Python36:
#         python.version: '3.6'
#         python.command: 'python'
#       Python37:
#         python.version: '3.7'
#         python.command: 'python'
#       PyPy3:
#         python.version: 'pypy3'
#         python.command: 'python'
#   steps:
#   - template: azure-pipelines-steps.yml