
yml = []

yml.append("""
# THIS FILE IS AUTOGENERATED -- DO NOT EDIT DIRECTLY
# Edit the Python script in this same folder instead, and then run it to
# regenerate this file.

name: Build wheels
on: [push]

jobs:
""")

# Mac & Windows builds
yml.append("""
  mac_windows:

    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8, 3.9]
        platform: [macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools wheel cffi>=1.0.0
    - name: Build
      run: |
        cd bindings
        python setup.py bdist_wheel
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: build-${{ matrix.platform }}-${{ matrix.python-version }}
        path: dist
""")

# manylinuxes
for pyver in ['35', '36', '37', '38', '39']:
    # There seems to be no way (as of 2020-02-13) to accomplish this in the YAML
    # (unlike in Azure Pipelines)
    if pyver in ['38', '39']:
        pycommand = f'/opt/python/cp{pyver}-cp{pyver}/bin/python'
    else:
        pycommand = f'/opt/python/cp{pyver}-cp{pyver}m/bin/python'

    yml.append(f"""
  manylinux-{pyver}:

    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{{{ matrix.python-version }}}}
      uses: actions/setup-python@v2
      with:
        python-version: ${{{{ matrix.python-version }}}}
    - name: Install dependencies
      run: |
        {pycommand} -m pip install --upgrade pip
        {pycommand} -m pip install --upgrade setuptools wheel auditwheel cffi>=1.0.0
    - name: Build
      run: |
        cd bindings
        {pycommand} setup.py bdist_wheel
    - name: Run auditwheel
      run: |
        cd bindings
        mkdir dist/wheelhouse
        {pycommand} -m auditwheel repair -w dist/wheelhouse/ dist/*.whl
        rm dist/*.whl
        mv dist/wheelhouse/* ../dist/
        rm -rf dist
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: build-manylinux-{pyver}
        path: dist
""")

# And finally, write the output file
with open('wheels.yml', 'w', encoding='utf-8') as f:
    f.write(''.join(yml))
